name: Run pre-commit

on:
  push:
    branches: ['**']         # Runs on every push to any branch
  pull_request:              # Runs on every PR, regardless of branch

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Adjust if needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit mypy black isort ruff

      - name: Run pre-commit
        run: pre-commit run --all-files
